#
# This is a generated file.
#

api.version=v2.0
entity.class.name=com.liferay.headless.commerce.admin.catalog.dto.v2_0.ProductConfiguration
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Commerce.Admin.Catalog)
osgi.jaxrs.resource=true